spring:
  application:
    name: GAE

  profiles:
    active: dev

logging:
  level:
    org.fh.gae: info
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] - [%t] - [%level] %c{40} - %m%n"


gae:
  instance-id: 1

  server:
    port: 9000
    host: 0.0.0.0

    # 用于处理长时间业务的worker线程池最大线程数;
    max-worker-thread: 10
    # NIO线程数, 默认为CPU核心数*2
    nio-thread: 6


  index:
    file:
      enable: true
      path: .
      name: mock-idx.txt
      incr-path: /Users/whf/projects/open/gae/src/main/resources/mock
      incr-name: gae.idx.incr
      incr-interval: 500

    kafka:
      enable: false
      addr: host:port
      topic: gae-idx

    redis:
      enable: false

  dict:
    ip: data/ipdict.txt

  min-unit-amount: 10000